# Project C - Wavelets

In [2]:
import numpy as np
import numpy.fft as npf
import matplotlib
import matplotlib.pyplot as plt
import time
import imagetools.projectC as im

# Part 1

In [12]:
np.random.choice(np.array([1,0]), size=5, replace=True, p=[self._p,1-self._p])

NameError: name 'self' is not defined

In [13]:
# (5,8,3)
p = .5
nonzero_entries = np.random.choice(np.array([0,1]), size=5, p=[p,1-p])

_H_random_mask = np.diag(nonzero_entries)
x = np.random.rand(5)
print(x)
np.matmul(np.diag(np.array([0, 0, 0, 0, 1])),x)

NameError: name 'ishape' is not defined

In [367]:
# (5,8,3)
# set proportion of the pixels to 0, as described in https://piazza.com/class/jt1dcjigm6n2ke?cid=297
p = .5

oshape = x.shape

def rand_diag(prob):
    nonzero_entries = np.random.choice(np.array([0,1]), size=oshape[0], p=[prob,1-prob])
    diagonal_random = np.diag(nonzero_entries)
    _H_random_mask = rand_diag(p)
    return diagonal_random

_H_random_mask = np.zeros(oshape)

for dim in range(len(oshape)):
    if len(oshape) or isinstance(oshape,int):
        # first dimension, build rand diag
        _H_random_mask = rand_diag(p)
        break
    
    if len(oshape)==2:
        _H_random_mask[:,]
    elif dim==1:
        # second dimension,
        _H_random_mask[:,:] = _H_random_mask[..., np.newaxis]
        _H_random_mask =  np.concatenate((_H_random_mask, rand_diag(p)[...,np.newaxis]), axis=0)
    else:
        _H_random_mask =  np.concatenate((_H_random_mask, rand_diag(p)[...,np.newaxis]), axis=0)
        
_H_random_mask = _H_random_mask.T
print(_H_random_mask)
print(x.shape)
print(_H_random_mask.shape)

ValueError: all the input arrays must have same number of dimensions

In [ ]:
if input_1d:
            # random masking in the 1D case
            nonzero_entries = np.random.choice(np.array([0,1]), size=oshape, p=[prob,1-prob])
            diagonal_random = np.diag(nonzero_entries)
            self._H_random_mask = rand_diag(p)
        else:
            # input is 3d, still need to test for 2D
            self._H_random_mask = np.random.choice(np.array([0,1]), size=ishape[:2], p=[p,1-p]).T
            
        def rand_diag(prob):
            nonzero_entries = np.random.choice(np.array([0,1]), size=oshape[0], p=[prob,1-prob])
            diagonal_random = np.diag(nonzero_entries)
            return diagonal_random

        
        final_dim = oshape[-1]
        for dim in range(final_dim):
            if dim==0:
                self._H_random_mask = rand_diag(p)
            elif dim==1:
                self._H_random_mask = _H_random_mask[..., np.newaxis]
                self._H_random_mask =  np.concatenate((_H_random_mask, rand_diag(p)[...,np.newaxis]), axis=2)
            else:
                self._H_random_mask =  np.concatenate((_H_random_mask, rand_diag(p)[...,np.newaxis]), axis=2)
        if len(oshape > 1):
            self._H_random_mask = self._H_random_mask.T

In [477]:
# (5,8,3)
# set proportion of the pixels to 0, as described in https://piazza.com/class/jt1dcjigm6n2ke?cid=297
p = .9

x = np.random.rand(5,5,3)

ishape = x.shape

_H_random_mask = np.random.choice(np.array([0,1]), size=ishape, p=[p,1-p])

print(x)
print(_H_random_mask*x)

[[[0.05540044 0.61612798 0.77660456]
  [0.72906018 0.69913066 0.61816245]
  [0.23184483 0.90843878 0.31020286]
  [0.98658995 0.27293091 0.06894247]
  [0.28587837 0.49750166 0.876194  ]]

 [[0.79170379 0.03233543 0.90181322]
  [0.67664679 0.46368    0.00677248]
  [0.89008688 0.6453683  0.25723056]
  [0.69421697 0.47249477 0.21871069]
  [0.59612908 0.29620214 0.31730659]]

 [[0.9317071  0.73943046 0.37426362]
  [0.63363746 0.53531525 0.10055848]
  [0.62005495 0.8109993  0.47980345]
  [0.55866083 0.66926256 0.72193101]
  [0.92937667 0.42054774 0.98642323]]

 [[0.88682776 0.29117875 0.41951059]
  [0.80323865 0.8635376  0.79562356]
  [0.05347148 0.34429212 0.61473886]
  [0.1888238  0.70403583 0.89279735]
  [0.37211979 0.38679525 0.57108995]]

 [[0.73327502 0.83359269 0.06750419]
  [0.27716352 0.36032233 0.95476889]
  [0.41103312 0.85297736 0.00717567]
  [0.29853304 0.01717533 0.96433599]
  [0.47291538 0.96605294 0.33760376]]]
[[[0.         0.         0.        ]
  [0.         0.         0. 

In [472]:
print(x)

[[[0.77972996 0.18152966 0.43967464]
  [0.49438957 0.90739938 0.81743948]
  [0.17728702 0.96555325 0.05756335]
  [0.10183216 0.53977828 0.18919448]
  [0.9834511  0.61755771 0.87305111]]

 [[0.62306059 0.6633699  0.36486083]
  [0.88705909 0.7407432  0.81855896]
  [0.67350407 0.67821365 0.51327586]
  [0.11370571 0.64570909 0.91656686]
  [0.62041617 0.70344787 0.3326518 ]]

 [[0.29935225 0.19250395 0.84445417]
  [0.01547683 0.62209895 0.03053269]
  [0.70545233 0.15772355 0.52952796]
  [0.97760461 0.51789717 0.09844417]
  [0.90985162 0.53807055 0.85521653]]

 [[0.39943751 0.85530627 0.22362583]
  [0.96732176 0.61321578 0.96853988]
  [0.42005585 0.62612011 0.2014741 ]
  [0.73909545 0.43933817 0.45591049]
  [0.161664   0.56432164 0.39860938]]

 [[0.20104173 0.30239045 0.33141183]
  [0.75827276 0.7154608  0.47564833]
  [0.71700357 0.89614679 0.22893033]
  [0.48423965 0.37612438 0.35415592]
  [0.4771141  0.8752527  0.19056261]]]


In [396]:
np.matmul(_H_random_mask,x)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [414]:
# 1 dim case
x = np.random.rand(5,1)

print(_H_random_mask.T.shape)
print(x)
print(np.matmul(_H_random_mask.T,x).shape)
print(np.matmul(_H_random_mask,x))

(5, 1)
[[0.5141788 ]
 [0.22750468]
 [0.55561076]
 [0.41910028]
 [0.47125376]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 1)

In [362]:
# 2,3 dim case
x = np.random.rand(5,3)

print(_H_random_mask.shape)
print(x)
print(np.matmul(_H_random_mask,x).shape)
print(np.matmul(_H_random_mask,x))

(2, 5, 5)
[[0.35718838 0.93875931 0.40521904]
 [0.82704783 0.09037045 0.8081872 ]
 [0.7927779  0.90733299 0.42221935]
 [0.49521455 0.51078003 0.37933761]
 [0.00970704 0.87565342 0.14322204]]
(2, 5, 3)
[[[0.35718838 0.93875931 0.40521904]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.49521455 0.51078003 0.37933761]
  [0.00970704 0.87565342 0.14322204]]

 [[0.35718838 0.93875931 0.40521904]
  [0.         0.         0.        ]
  [0.7927779  0.90733299 0.42221935]
  [0.49521455 0.51078003 0.37933761]
  [0.00970704 0.87565342 0.14322204]]]


In [392]:
print(np.random.choice(np.array([0,1]), size=(5,5), p=[.5,1-.5]))


[[0 0 0 1 0]
 [1 1 1 1 0]
 [1 1 0 0 1]
 [0 0 0 1 0]
 [0 0 0 1 0]]


In [379]:
x = np.array([np.diag([0,1,0,1]),np.diag([0,1,0,1]),np.diag([0,1,0,1])])
print(x.shape)

(3, 4, 4)


In [389]:
print(np.random.rand(3,4,4))
print(np.matmul(x.T,np.random.rand(4,4)))

[[[0.81920174 0.3253478  0.52403706 0.63658965]
  [0.93803443 0.82480523 0.91979668 0.63270916]
  [0.1558862  0.83771545 0.3214954  0.10404415]
  [0.24647432 0.57163563 0.95134018 0.9355127 ]]

 [[0.28629797 0.65510603 0.47567569 0.39278079]
  [0.91493624 0.77852187 0.27791603 0.4458384 ]
  [0.92907933 0.67961094 0.4082822  0.7256771 ]
  [0.57483329 0.08918796 0.3587183  0.45388215]]

 [[0.01789251 0.49144219 0.25563789 0.63636949]
  [0.33326099 0.1419965  0.88497724 0.22366334]
  [0.26532449 0.11829723 0.05105047 0.50347354]
  [0.79993308 0.42932696 0.85766658 0.43515814]]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [176]:
print(_H_random_mask)

[[0 0 1 1 1]
 [1 1 1 1 0]
 [0 0 0 0 0]
 [1 0 1 0 1]
 [1 0 1 0 1]]


In [ ]:
def verify_q1(2):
    nu_fft = im.kernel2fft(nu,x.shape[0],x.shape[1])
    mu_fft = np.conjugate(nu_fft)
    lhs,rhs = dot_product(im.convolvefft(x,nu_fft),y),dot_product(x,im.convolvefft(y,mu_fft))
    np.isclose(lhs,rhs),lhs,rhs

Work together as described here

In [1]:
def dwt(x, J, h, h):
    pass

SyntaxError: duplicate argument 'h' in function definition (<ipython-input-1-3c08a0a4a192>, line 4)

In [2]:
import numpy as np
def softthresh(z, t):
    new_z = (z - np.sign(z-t) * t) * np.maximum(np.abs(z)-t,0).astype(bool) # conversion to bool maps to (0,1)
    return new_z

In [3]:
# x is negative,threshold is negative
x = -np.random.rand(3,2) * 5
print(x)
print(softthresh(x,-5))
# x is negative,threshold is positive
print(softthresh(x,5))

# x is positive,threshold is negative
x = np.random.rand(3,2) * 5
print(x)
print(softthresh(x,-5))
# x is positive,threshold is positive
print(softthresh(x,5))

[[-2.50255565 -4.38294809]
 [-0.44161194 -2.93732861]
 [-1.10295096 -2.64660882]]
[[2.49744435 0.61705191]
 [4.55838806 2.06267139]
 [3.89704904 2.35339118]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[4.44560314 2.30206049]
 [2.16346391 0.12140339]
 [1.33057788 4.41575301]]
[[9.44560314 7.30206049]
 [7.16346391 5.12140339]
 [6.33057788 9.41575301]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [46]:
np.sign(np.ones((5,5)) - 4)

array([[-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.]])