# Project C - Wavelets

In [1]:
%load_ext autoreload
%autoreload 2
import numpy as np
import numpy.fft as npf
import matplotlib
import matplotlib.pyplot as plt
import time
import imagetools.projectC as im

%matplotlib notebook

# Test

In [2]:
lady = 'assets/lady.png'

x = plt.imread(lady)
nu = im.kernel('box',tau=5)
y = im.convolve(x,nu,boundary='periodical')

# Section 2

Work together as described here

In [1]:
def dwt(x, J, h, h):
    pass

SyntaxError: duplicate argument 'h' in function definition (<ipython-input-1-3c08a0a4a192>, line 4)

In [2]:
import numpy as np
def softthresh(z, t):
    new_z = (z - np.sign(z-t) * t) * np.maximum(np.abs(z)-t,0).astype(bool) # conversion to bool maps to (0,1)
    return new_z

In [3]:
# x is negative,threshold is negative
x = -np.random.rand(3,2) * 5
print(x)
print(softthresh(x,-5))
# x is negative,threshold is positive
print(softthresh(x,5))

# x is positive,threshold is negative
x = np.random.rand(3,2) * 5
print(x)
print(softthresh(x,-5))
# x is positive,threshold is positive
print(softthresh(x,5))

[[-2.50255565 -4.38294809]
 [-0.44161194 -2.93732861]
 [-1.10295096 -2.64660882]]
[[2.49744435 0.61705191]
 [4.55838806 2.06267139]
 [3.89704904 2.35339118]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[4.44560314 2.30206049]
 [2.16346391 0.12140339]
 [1.33057788 4.41575301]]
[[9.44560314 7.30206049]
 [7.16346391 5.12140339]
 [6.33057788 9.41575301]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [46]:
np.sign(np.ones((5,5)) - 4)

array([[-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.]])